# Site settings
title: Akshen Doke
description: ML Engineer | AWS Certified | Certified Scrum Product Owner
theme: jekyll-theme-minimal

# Personal info
name: Akshen Doke
email: doke.akshen@gmail.com

# Social links
github:
  username: akshen
linkedin:
  username: akshen

# Logo/image
logo: /images/profile.jpg

# Build settings
markdown: kramdown

# Google Analytics Tracking ID
google_analytics: G-XN3HH3068R
